### ISSUE TITLE
Private Repos?

### ISSUE THREAD

**Issue by CaseyHaralson** [iwatakeshi/gitly#26]
Would it be possible to use this to pull from private repos?

**Comment by iwatakeshi** [comment]
Hi. The way gitly works is by using `axios` to call the archiving api endpoints of GitHub (and the like). I'm not familiar with private repos so I apologize in advance, but I would think one may need some kind of token/credential. `gitly` allows you to pass headers directly to axios via the `GitlyOptions`'s `headers` property.

**Comment by CaseyHaralson** [comment]
What do you think about having the option to spawn a git command that runs "git clone [repo]"? My use case is cloning repos for templating purposes and it would be nice to use my git credentials to clone repos that aren't public (like private company repos).

**Comment by iwatakeshi** [comment]
I think it can be a good idea. [This thread ](https://stackoverflow.com/questions/2505096/clone-a-private-repository-github)from Stack Overflow can be used as an inspiration. Maybe adding a `backend` option so that it can be used as follows: `gitly('clone [repo]', { backend: 'git' })`. It's just a thought. Maybe just detecting the keyword `clone` would suffice. At the moment, my hands are tied so I do not have an ETA on when this feature can be added (sincere apologies), but you are more than welcomed to contribute to the project.

**Comment by CaseyHaralson** [comment]
Added a PR for this: https://github.com/iwatakeshi/gitly/pull/27

What do you think?

**Comment by iwatakeshi** [comment]
I greatly appreciate your contribution @CaseyHaralson! Thank you! I think this should be good for now. I'll go ahead and publish a new version soon. In the future, we may consider adding an option for a username and password/token to clone private repos as well. I'll think about it and improve when I get the time, but I welcome anyone to contribute to make gitly better.

**Comment by iwatakeshi** [comment]
New version published! I did make a few improvements (to handle caching), but I haven't tackled the username and password part yet. Again, thank you! Feel free to make improvements!

**Comment by CaseyHaralson** [comment]
It doesn't look like this is working anymore. It makes a folder, but there is no content.

**Comment by iwatakeshi** [comment]
Well, dang it 😅. I'll see if I can get to it this evening again.

**Comment by CaseyHaralson** [comment]
I'll try and debug a bit too and see if I can figure out whats happening :)

**Comment by iwatakeshi** [comment]
Much appreciated!

**Comment by CaseyHaralson** [comment]
I figured out a few things:
- when the clone is run, it clones to .gitly but as a folder like "path/repo/master.tar.gz" and not as an actual tar archive. It's just a folder with the repo inside of it along with the ".git" folder. This causes the tar archive extraction to fail because its source is a folder.
- If the folder already exists in the .gitly folder then the clone returns a 128 code (instead of 0). This causes the clone to fail. 

So, I have a few questions:
- does the project need to assume that a .tar.gz archive is being downloaded?
- can the "repo/master.tar.gz" folder be removed before the clone is performed? I would expect an up-to-date repo to be extracted vs an old version of the repo. This would also fix the 128 code being returned sometimes.
- I assume we would want the .git folder from being included in the destination?

I can help but wasn't sure about what assumptions the repo was making.

**Comment by iwatakeshi** [comment]
> does the project need to assume that a .tar.gz archive is being downloaded?

I thought it about it... I wasn't sure if the folder cloned by git was already extracted or compressed. I assumed the latter which is probably incorrect on my part. I would prefer that it's compressed since it would save space unless I'm missing something 😅. As far as the which type of archive to use, I'm opened minded. I use .tar.gz for consistency.

 >can the "repo/master.tar.gz" folder be removed before the clone is performed? I would expect an up-to-date repo to be extracted vs an old version of the repo. This would also fix the 128 code being returned sometimes.

gitly caches the repository under `.gitly/` and then extracts the cache first. The `options.cache` set to `false` would make gitly always use the latest version. If possible, I'm trying to keep it consistent with the original behavior. But, I like to hear your thoughts on that.

**Comment by CaseyHaralson** [comment]
I made a pr that hopefully fits with everything else. 

I checked the git command and it does have a an option to pull a remote repo archive (git archive --remote <repo>), but it isn't supported on github and some other servers too so, sadly, that wouldn't work.

I kept the current code to where it clones into the .gitly folder, removes the .git folder, and the copies the folder contents to the destination. I'm not super excited about the cloned folder looking like an archive (but really being a folder), but it is a bit more consistent with the archive download...so... I don't know.

**Comment by iwatakeshi** [comment]
I was also working on the fix which I think it works and I did take some inspiration from yours after I compared it with mine, specifically removing previous caches and running asynchronous tasks within the `.on` methods. It can be seen at https://github.com/iwatakeshi/gitly/compare/master...fix/clone or https://github.com/iwatakeshi/gitly/commit/0b8761487f28ea4a79de5daff0f694b010c9b9d4. I definitely give credits to you for the work you've put into. Let me know what you think.

**Comment by CaseyHaralson** [comment]
It looks good. It's working for me. I like the add of the clone depth and making an archive too.

I would only suggest removing the .git folder after the clone and before making the archive. That should make the archive look like the archives pulled from axios.

**Comment by iwatakeshi** [comment]
> I would only suggest removing the .git folder after the clone and before making the archive. That should make the archive look like the archives pulled from axios.

When I do that, the tests would fail. Tar archives the cloned directory and then the cloned directory would get deleted. There's a little more work involved since gitly now needs to archive the directory, delete the directory, then un-archive the archived directory to another location (destination). All for consistency 😅.

**Comment by iwatakeshi** [comment]
New version published!

**Comment by CaseyHaralson** [comment]
See if this pr helps explain what I was talking about: https://github.com/iwatakeshi/gitly/pull/30/files

Git clone also creates a .git folder that contains branch and repo information which isn't needed when making the archive.

**Comment by CaseyHaralson** [comment]
It looks like you got the codeql error to go away too! Great!

**Comment by iwatakeshi** [comment]
Merged and published! Thank you very much @CaseyHaralson!

**Comment by CaseyHaralson** [comment]
Thanks for working with me @iwatakeshi!

**Comment by iwatakeshi** [comment]
Absolutely! 👍
